#!/usr/bin/env bash
# Compile the JSX surface into the single file the shells load.
#
# This is NOT part of running the app — static/airtight-kit.js is committed, so
# `uvicorn surface.app:app` works on a clean clone with no Node installed. Run
# this only after editing something under surface/ui/.
#
#     bash surface/build.sh
#
# React and ReactDOM stay external: they load as UMD globals from static/vendor/
# and the aliases below map the bare specifiers onto them.

set -euo pipefail

cd "$(dirname "$0")"

npx --yes esbuild@0.25.0 ui/main.jsx \
  --bundle \
  --format=iife \
  --target=es2020 \
  --jsx=transform \
  --alias:react=./ui/vendor-shim/react.js \
  --alias:react-dom/client=./ui/vendor-shim/react-dom-client.js \
  --minify \
  --legal-comments=none \
  --banner:js='/* Generated by surface/build.sh from surface/ui/ — do not edit by hand. */' \
  --outfile=static/airtight-kit.js

printf '\nbuilt static/airtight-kit.js (%s)\n' "$(du -h static/airtight-kit.js | cut -f1)"
